[dev]
  command = "next dev -p 3000"
  port = 8888
  targetPort = 3000

[build]
  command = "yarn build"
  functions = "api"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200